from django.urls import path

from . import views


app_name = "productions"
urlpatterns = [
    path("", views.ProductionListView.as_view(), name="list"),
    path("cuentas/registro/", views.UserRegistrationView.as_view(), name="register"),
    path("cuentas/registro/listo/", views.UserRegistrationDoneView.as_view(), name="register_done"),
    path("usuarios/", views.UserListView.as_view(), name="user_list"),
    path("usuarios/<int:pk>/acceso/", views.UserAccessUpdateView.as_view(), name="user_access"),
    path("salud/", views.health, name="health"),
    path("sesion/csrf/", views.csrf_token, name="csrf_token"),
    path("manifest.webmanifest", views.manifest, name="manifest"),
    path("service-worker.js", views.service_worker, name="service_worker"),
    path("producciones/nueva/", views.ProductionCreateView.as_view(), name="create"),
    path("producciones/<int:pk>/editar/", views.ProductionUpdateView.as_view(), name="update"),
    path("catalogos/", views.CatalogDashboardView.as_view(), name="catalogs"),
    path("catalogos/laminas/", views.ProductLaminaColorListView.as_view(), name="product_lamina_colors"),
    path("catalogos/clientes/nuevo/", views.CustomerCreateView.as_view(), name="customer_create"),
    path("catalogos/vehiculos/nuevo/", views.VehicleCreateView.as_view(), name="vehicle_create"),
    path("catalogos/trabajadores/nuevo/", views.WorkerCreateView.as_view(), name="worker_create"),
    path("catalogos/tarifas/nueva/", views.RateCreateView.as_view(), name="rate_create"),
    path("producciones/<int:pk>/", views.ProductionDetailView.as_view(), name="detail"),
    path("producciones/<int:pk>/cuadrillas/consolidado/", views.CrewControlView.as_view(), name="crew_control"),
    path("producciones/<int:pk>/reporte/", views.ProductionReportView.as_view(), name="report"),
    path("producciones/<int:pk>/reporte-recepcion.xlsx", views.ReceptionReportXlsxView.as_view(), name="reception_report_xlsx"),
    path("producciones/<int:pk>/tareo-recepcion.xlsx", views.ReceptionTareoXlsxView.as_view(), name="reception_tareo_xlsx"),
    path("producciones/<int:pk>/tareo-recepcion.pdf", views.ReceptionTareoPdfView.as_view(), name="reception_tareo_pdf"),
    path("producciones/<int:pk>/reporte-recepcion.pdf", views.ReceptionReportPdfView.as_view(), name="reception_report_pdf"),
    path("producciones/<int:pk>/estado/", views.ProductionTransitionView.as_view(), name="transition"),
    path("producciones/<int:pk>/eliminar-definitivo/", views.ProductionHardDeleteView.as_view(), name="hard_delete"),
    path("producciones/<int:pk>/tuneles/llenada/nueva/", views.TunnelFillCreateView.as_view(), name="tunnel_fill_create"),
    path("producciones/<int:pk>/tuneles/registro/nuevo/", views.TunnelEntryCreateView.as_view(), name="tunnel_entry_create"),
    path("producciones/<int:pk>/tuneles/reporte.xlsx", views.TunnelReportXlsxView.as_view(), name="tunnel_report_xlsx"),
    path("producciones/<int:pk>/tuneles/<int:tunnel_pk>/reporte.xlsx", views.TunnelReportXlsxView.as_view(), name="tunnel_report_xlsx_by_tunnel"),
    path("producciones/<int:pk>/tuneles/reporte.pdf", views.TunnelReportPdfView.as_view(), name="tunnel_report_pdf"),
    path("producciones/<int:pk>/tuneles/<int:tunnel_pk>/reporte.pdf", views.TunnelReportPdfView.as_view(), name="tunnel_report_pdf_by_tunnel"),
    path("producciones/<int:pk>/tuneles/llenada/<int:fill_pk>/captura/", views.TunnelBatchEntryView.as_view(), name="tunnel_batch"),
    path("producciones/<int:pk>/tuneles/llenada/<int:fill_pk>/transferir/", views.TunnelFillTransferView.as_view(), name="tunnel_fill_transfer"),
    path("producciones/<int:pk>/tuneles/llenada/<int:fill_pk>/eliminar/", views.TunnelFillDeleteView.as_view(), name="tunnel_fill_delete"),
    path(
        "producciones/<int:pk>/tuneles/llenada/<int:fill_pk>/registro/<int:entry_pk>/eliminar/",
        views.TunnelEntryDeleteView.as_view(),
        name="tunnel_entry_delete",
    ),
    path(
        "producciones/<int:pk>/tuneles/llenada/<int:fill_pk>/rack/<int:rack_pk>/estado/",
        views.TunnelRackTransitionView.as_view(),
        name="tunnel_rack_transition",
    ),
    path("producciones/<int:pk>/tuneles/llenada/<int:fill_pk>/estado/", views.TunnelFillTransitionView.as_view(), name="tunnel_fill_transition"),
    path("producciones/<int:pk>/recepcion/nuevo/", views.ReceptionCreateView.as_view(), name="reception_create"),
    path("producciones/<int:pk>/recepcion/carro/crear/", views.ReceptionCarCreateView.as_view(), name="reception_car_create"),
    path("producciones/<int:pk>/recepcion/carro/<int:vehicle_pk>/eliminar/", views.ReceptionCarDeleteView.as_view(), name="reception_car_delete"),
    path("producciones/<int:pk>/recepcion/carro/<int:vehicle_pk>/cerrar/", views.ReceptionCarCloseView.as_view(), name="reception_car_close"),
    path("producciones/<int:pk>/nuqueras/nuevo/", views.NuqueraCreateView.as_view(), name="nuquera_create"),
    path("producciones/<int:pk>/nuqueras/crear-trabajador/", views.NuqueraWorkerQuickCreateView.as_view(), name="nuquera_worker_quick_create"),
    path("producciones/<int:pk>/nuqueras/tareo.xlsx", views.NuqueraTareoXlsxView.as_view(), name="nuquera_tareo_xlsx"),
    path("producciones/<int:pk>/nuqueras/tareo.pdf", views.NuqueraTareoPdfView.as_view(), name="nuquera_tareo_pdf"),
    path("producciones/<int:pk>/cuadrillas-tunel/nuevo/", views.TunnelCrewCreateView.as_view(), name="tunnel_crew_create"),
    path(
        "producciones/<int:pk>/cuadrillas-tunel/crear-cuadrilla/",
        views.TunnelCrewQuickCreateView.as_view(),
        name="tunnel_crew_quick_create",
    ),
    path("producciones/<int:pk>/placas/nuevo/", views.PlateCreateView.as_view(), name="plate_create"),
    path(
        "producciones/<int:pk>/placas/reporte.xlsx",
        views.PlateReportXlsxView.as_view(),
        name="plate_report_xlsx",
    ),
    path(
        "producciones/<int:pk>/placas/reporte.pdf",
        views.PlateReportPdfView.as_view(),
        name="plate_report_pdf",
    ),
    path(
        "producciones/<int:pk>/placas/iniciar-llenado/",
        views.PlateLoadStartView.as_view(),
        name="plate_load_start_selected",
    ),
    path(
        "producciones/<int:pk>/placas/<int:position_pk>/iniciar-llenado/",
        views.PlateLoadStartView.as_view(),
        name="plate_load_start",
    ),
    path(
        "producciones/<int:pk>/placas/<int:position_pk>/finalizar-carga/",
        views.PlateLoadCompleteView.as_view(),
        name="plate_load_complete",
    ),
    path(
        "producciones/<int:pk>/placas/<int:position_pk>/registrar-lanzamiento/",
        views.PlateLaunchRegisterView.as_view(),
        name="plate_launch_register",
    ),
    path(
        "producciones/<int:pk>/placas/<int:position_pk>/registrar-descarga/",
        views.PlateUnloadRegisterView.as_view(),
        name="plate_unload_register",
    ),
    path(
        "producciones/<int:pk>/placas/<int:position_pk>/limpiar-control-vacio/",
        views.PlateTimingResetView.as_view(),
        name="plate_timing_reset",
    ),
    path("producciones/<int:pk>/cuadrillas-placas/nuevo/", views.PlateCrewCreateView.as_view(), name="plate_crew_create"),
    path(
        "producciones/<int:pk>/cuadrillas-placas/crear-cuadrilla/",
        views.PlateCrewQuickCreateView.as_view(),
        name="plate_crew_quick_create",
    ),
    path("producciones/<int:pk>/empaque-tunel/nuevo/", views.TunnelPackagingCreateView.as_view(), name="tunnel_pack_create"),
    path("producciones/<int:pk>/empaque-tunel/calcular/", views.TunnelAutoPackagingView.as_view(), name="tunnel_pack_auto"),
    path(
        "producciones/<int:pk>/empaque-tunel/reporte.xlsx",
        views.PackagingReportXlsxView.as_view(report_kind="tunnel"),
        name="tunnel_pack_report_xlsx",
    ),
    path(
        "producciones/<int:pk>/empaque-tunel/reporte.pdf",
        views.PackagingReportPdfView.as_view(report_kind="tunnel"),
        name="tunnel_pack_report_pdf",
    ),
    path("producciones/<int:pk>/empaque-placas/nuevo/", views.PlatePackagingCreateView.as_view(), name="plate_pack_create"),
    path("producciones/<int:pk>/empaque-placas/saldo/manual/", views.PlateManualBalanceCreateView.as_view(), name="plate_pack_manual_balance"),
    path("producciones/<int:pk>/empaque-placas/saldo/inicial/", views.PlateInitialBalanceCreateView.as_view(), name="plate_pack_initial_balance"),
    path(
        "producciones/<int:pk>/empaque-placas/reporte.xlsx",
        views.PackagingReportXlsxView.as_view(report_kind="plate"),
        name="plate_pack_report_xlsx",
    ),
    path(
        "producciones/<int:pk>/empaque-placas/reporte.pdf",
        views.PackagingReportPdfView.as_view(report_kind="plate"),
        name="plate_pack_report_pdf",
    ),
    path("producciones/<int:pk>/empaque-placas/calcular/", views.PlateAutoPackagingView.as_view(), name="plate_pack_auto"),
    path("producciones/<int:pk>/empaque-placas/saldos/", views.PlateBalanceView.as_view(), name="plate_balance"),
    path("producciones/<int:pk>/empaque-placas/pallet/<int:pallet_pk>/estado/", views.PlatePalletStatusView.as_view(), name="plate_pallet_status"),
    path("producciones/<int:pk>/empaque-placas/movimiento/<int:line_pk>/eliminar/", views.PlatePalletLineDeleteView.as_view(), name="plate_pallet_line_delete"),
    path("producciones/<int:pk>/materiales/nuevo/", views.MaterialUsageCreateView.as_view(), name="material_create"),
    path("producciones/<int:pk>/costos/nuevo/", views.CostEntryCreateView.as_view(), name="cost_create"),
    path("producciones/<int:pk>/troquelado/nuevo/", views.TroqueladoCreateView.as_view(), name="troquelado_create"),
    path("producciones/<int:pk>/troquelado/crear-trabajador/", views.TroqueladoWorkerQuickCreateView.as_view(), name="troquelado_worker_quick_create"),
path("producciones/<int:pk>/troquelado/captura/", views.TroqueladoQuickCaptureView.as_view(), name="troquelado_quick_capture"),
    path("producciones/<int:pk>/nuqueras/captura/", views.NuqueraQuickCaptureView.as_view(), name="nuquera_quick_capture"),
    path("producciones/<int:pk>/troquelado/reporte.xlsx", views.TroqueladoReportXlsxView.as_view(), name="troquelado_report_xlsx"),
    path("producciones/<int:pk>/troquelado/reporte.pdf", views.TroqueladoReportPdfView.as_view(), name="troquelado_report_pdf"),
    path(
        "producciones/<int:pk>/registros/<str:module>/<int:entry_pk>/corregir/",
        views.OperationalEntryUpdateView.as_view(),
        name="operational_entry_update",
    ),
    path(
        "producciones/<int:pk>/registros/<str:module>/<int:entry_pk>/eliminar/",
        views.OperationalEntryDeleteView.as_view(),
        name="operational_entry_delete",
    ),
    path("producciones/<int:pk>/excel/<str:kind>/generar/", views.GenerateExcelView.as_view(), name="generate_excel"),
    path("producciones/<int:pk>/pdf/", views.ProductionPdfView.as_view(), name="production_pdf"),
    path("archivos/<int:pk>/descargar/", views.DownloadGeneratedFileView.as_view(), name="download_file"),
    path("api/sync-data/", views.sync_data_api, name="sync_data_api"),
    path("ads.txt", views.ads_txt, name="ads_txt"),
]
