# Generated by Django 5.2.16 on 2026-07-13 19:38

import productions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='platepackagingentry',
            name='plate_pallet_lte_50',
        ),
        migrations.RemoveConstraint(
            model_name='tunnelpackagingentry',
            name='tunnel_pallet_lte_77',
        ),
        migrations.AddField(
            model_name='templateversion',
            name='rules',
            field=models.JSONField(default=productions.models.default_template_rules),
        ),
        migrations.AlterField(
            model_name='tunnelentry',
            name='tray_count',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
