# Generated by Django 5.2.16 on 2026-07-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0002_remove_platepackagingentry_plate_pallet_lte_50_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['description', 'code']},
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('description', 'code'), name='uniq_product_description_code'),
        ),
    ]
