# Generated by Django 5.2.16 on 2026-07-13

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0003_allow_repeated_product_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionorder",
            name="number",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name="productionorder",
            constraint=models.UniqueConstraint(
                fields=("number",),
                condition=~Q(status="VOID"),
                name="uniq_active_production_number",
            ),
        ),
    ]
