# Generated by Django 5.2.16 on 2026-07-14 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0005_tunnelrack_max_trays'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_status',
            field=models.CharField(choices=[('ACTIVE', 'Activa'), ('PENDING', 'Pendiente de aprobación'), ('REJECTED', 'Rechazada')], default='ACTIVE', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='requested_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('JEFE_PROD', 'Jefe de producción'), ('RECEPCION', 'Responsable de recepción'), ('NUQUERAS', 'Responsable de nuqueras o perfilado'), ('TUNEL', 'Supervisor de túnel'), ('CUAD_TUNEL', 'Responsable de bandejas por cuadrilla'), ('ENV_PLACAS', 'Responsable de envasado en plaqueros'), ('CUAD_PLACAS', 'Responsable de cuadrillas de placas'), ('EMP_TUNEL', 'Responsable de empaque de túneles'), ('EMP_PLACAS', 'Responsable de empaque de placas'), ('MATERIALES', 'Responsable de materiales'), ('COSTOS', 'Responsable de costos'), ('GERENCIA', 'Gerencia o consulta'), ('AUDITOR', 'Auditor')], max_length=24),
        ),
    ]
