# Generated by Django 5.2.16 on 2026-07-16 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0009_repair_tunnel_crew_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatePositionTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('load_completed_at', models.DateTimeField(blank=True, null=True)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('launched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_plate_launches', to=settings.AUTH_USER_MODEL)),
                ('load_completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_plate_loads', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_timings', to='productions.plateposition')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plate_position_timings', to='productions.productionorder')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('production', 'position'), name='uniq_plate_position_timing')],
            },
        ),
    ]
