# Generated by Django 5.2.16 on 2026-07-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0010_platepositiontiming"),
    ]

    operations = [
        migrations.AddField(
            model_name="platepositiontiming",
            name="load_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platepositiontiming",
            name="unloaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platepositiontiming",
            name="load_started_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="started_plate_loads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="platepositiontiming",
            name="unloaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registered_plate_unloads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
