# Generated by Django 5.2.16 on 2026-07-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0014_platecarryoverbalance_platepallet_platepalletline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaassignment',
            name='shift',
            field=models.CharField(choices=[('DAY', 'Día'), ('AFTERNOON', 'Tarde'), ('NIGHT', 'Noche'), ('MIXED', 'Mixto')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nuqueraentry',
            name='shift',
            field=models.CharField(choices=[('DAY', 'Día'), ('AFTERNOON', 'Tarde'), ('NIGHT', 'Noche'), ('MIXED', 'Mixto')], max_length=10),
        ),
        migrations.AlterField(
            model_name='plateentry',
            name='shift',
            field=models.CharField(choices=[('DAY', 'Día'), ('AFTERNOON', 'Tarde'), ('NIGHT', 'Noche'), ('MIXED', 'Mixto')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='shift',
            field=models.CharField(choices=[('DAY', 'Día'), ('AFTERNOON', 'Tarde'), ('NIGHT', 'Noche'), ('MIXED', 'Mixto')], max_length=10),
        ),
    ]
