# Generated by Django 5.2.16 on 2026-07-18 00:56

import django.db.models.deletion
from django.db import migrations, models


def backfill_unambiguous_products(apps, schema_editor):
    PlateCrewEntry = apps.get_model('productions', 'PlateCrewEntry')
    PlateEntry = apps.get_model('productions', 'PlateEntry')
    for crew_entry in PlateCrewEntry.objects.filter(product__isnull=True).iterator():
        product_ids = list(
            PlateEntry.objects.filter(
                production_id=crew_entry.production_id,
                position_id=crew_entry.position_id,
                is_active=True,
            )
            .values_list('product_id', flat=True)
            .distinct()[:2]
        )
        if len(product_ids) == 1:
            PlateCrewEntry.objects.filter(pk=crew_entry.pk).update(
                product_id=product_ids[0]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0015_add_afternoon_shift'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='platecrewentry',
            name='uniq_plate_crew_page',
        ),
        migrations.AddField(
            model_name='platecrewentry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plate_crew_entries', to='productions.product'),
        ),
        migrations.RunPython(
            backfill_unambiguous_products,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='platecrewentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('product__isnull', False)), fields=('production', 'position', 'page', 'crew', 'product'), name='uniq_plate_crew_product_page'),
        ),
    ]
