# Generated by Django 5.2.16 on 2026-07-20 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0017_tunnelrack_closure'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tunnelcrewentry',
            name='uniq_active_tunnel_rack_crew',
        ),
        migrations.AddField(
            model_name='tunnelcrewentry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tunnel_crew_entries', to='productions.product'),
        ),
        migrations.AddConstraint(
            model_name='tunnelcrewentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('rack__isnull', False)), fields=('fill', 'rack', 'product', 'crew'), name='uniq_active_tunnel_rack_product_crew'),
        ),
    ]
