# Generated by Django 5.2.16 on 2026-07-21 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0018_remove_tunnelcrewentry_uniq_active_tunnel_rack_crew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platecarryoverbalance',
            name='source_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carryover_balance', to='productions.plateentry'),
        ),
    ]
