# Generated by Django 5.2.16 on 2026-08-03 09:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0022_link_pp_product_lamina_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionCarTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_reception_cars', to=settings.AUTH_USER_MODEL)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reception_car_timings', to='productions.productionorder')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productions.vehicle')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('production', 'vehicle'), name='uniq_reception_car_timing')],
            },
        ),
    ]
