# Generated by Django 5.2.16 on 2026-08-03 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0023_reception_car_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptioncartiming',
            name='car_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='receptioncartiming',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productions.product'),
        ),
    ]
