# Generated by Django 5.2.16 on 2026-08-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0024_reception_car_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptioncartiming',
            name='crews',
            field=models.ManyToManyField(blank=True, related_name='reception_car_timings', to='productions.crew'),
        ),
    ]
