# Generated by Django 5.2.16 on 2026-08-05 15:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0025_reception_car_crews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaassignment',
            name='area',
            field=models.CharField(choices=[('RECEPTION', 'Recepción'), ('NUQUERAS', 'Nuqueras'), ('TUNNEL', 'Túnel'), ('TUNNEL_CREW', 'Cuadrillas de túnel'), ('PLATES', 'Envasado en placas'), ('PLATE_CREW', 'Cuadrillas de placas'), ('TUNNEL_PACK', 'Empaque de túneles'), ('PLATE_PACK', 'Empaque de placas'), ('MATERIALS', 'Materiales'), ('COSTS', 'Costos'), ('TROQUELADO', 'Troquelado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('JEFE_PROD', 'Jefe de producción'), ('RECEPCION', 'Responsable de recepción'), ('NUQUERAS', 'Responsable de nuqueras o perfilado'), ('TUNEL', 'Supervisor de túnel'), ('CUAD_TUNEL', 'Responsable de bandejas por cuadrilla'), ('ENV_PLACAS', 'Responsable de envasado en plaqueros'), ('CUAD_PLACAS', 'Responsable de cuadrillas de placas'), ('EMP_TUNEL', 'Responsable de empaque de túneles'), ('EMP_PLACAS', 'Responsable de empaque de placas'), ('MATERIALES', 'Responsable de materiales'), ('COSTOS', 'Responsable de costos'), ('TROQUELADO', 'Responsable de troquelado'), ('GERENCIA', 'Gerencia o consulta'), ('AUDITOR', 'Auditor')], max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='requested_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('JEFE_PROD', 'Jefe de producción'), ('RECEPCION', 'Responsable de recepción'), ('NUQUERAS', 'Responsable de nuqueras o perfilado'), ('TUNEL', 'Supervisor de túnel'), ('CUAD_TUNEL', 'Responsable de bandejas por cuadrilla'), ('ENV_PLACAS', 'Responsable de envasado en plaqueros'), ('CUAD_PLACAS', 'Responsable de cuadrillas de placas'), ('EMP_TUNEL', 'Responsable de empaque de túneles'), ('EMP_PLACAS', 'Responsable de empaque de placas'), ('MATERIALES', 'Responsable de materiales'), ('COSTOS', 'Responsable de costos'), ('TROQUELADO', 'Responsable de troquelado'), ('GERENCIA', 'Gerencia o consulta'), ('AUDITOR', 'Auditor')], max_length=24),
        ),
        migrations.CreateModel(
            name='TroqueladoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('observation', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('DAY', 'Día'), ('AFTERNOON', 'Tarde'), ('NIGHT', 'Noche'), ('MIXED', 'Mixto')], max_length=10)),
                ('cajas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('kg_por_caja', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productions.productionorder')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productions.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
