# Generated by Django 5.2.16 on 2026-08-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0027_troquelado_crew_and_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
