# Generated by Django 5.2.16 on 2026-09-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0033_create_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnelpackagingentry',
            name='source_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_status',
            field=models.CharField(choices=[('ACTIVE', 'Activa'), ('PENDING', 'Pendiente de aprobación'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=12),
        ),
    ]
