# Generated by Django 5.2.16 on 2026-09-18 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0035_neutralize_admin_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='costentry',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_entries', to='productions.crew'),
        ),
        migrations.AddField(
            model_name='costentry',
            name='tareo_area',
            field=models.CharField(choices=[('GENERAL', 'Cuadrilla general'), ('RECEPCION', 'Recepción'), ('NUQUERAS', 'Nuqueras'), ('TUNEL', 'Túnel'), ('PLACAS', 'Placas'), ('EMPAQUE_TUNEL', 'Empaque de túnel'), ('EMPAQUE_PLACAS', 'Empaque de placas'), ('TROQUELADO', 'Troquelado')], default='GENERAL', max_length=30),
        ),
        migrations.AddField(
            model_name='costentry',
            name='tareo_reference',
            field=models.CharField(blank=True, help_text='Cuadrilla, trabajador, turno o identificador del tareo al que pertenece el costo.', max_length=160),
        ),
        migrations.AddField(
            model_name='costentry',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_entries', to='productions.worker'),
        ),
    ]
